### ISSUE TITLE
Please release v0.2.0 proper

### ISSUE THREAD

**Issue by chrisjsewell** [sponce24/aiida-abinit#13]
Heya @sponce24, could you release a v0.2.0 to PyPI?
I need a "non-prerelease" version, for use with https://github.com/aiidateam/aiida-common-workflows

**Comment by chrisjsewell** [comment]
I'd not also, if you want, you are welcome to transfer the package to https://github.com/aiidaplugins, this is just a central organisation to house plugins, that are not "officially" maintained by the aiidateam

**Comment by sponce24** [comment]
Hello @chrisjsewell 
The version `aiida-abinit 0.2.0a1` has been on PyPI for a long time https://pypi.org/project/aiida-abinit/
It is not a pre-release version. Is it ok to use that one for the aiida-common-workflows ? 

Best, 
Samuel

**Comment by chrisjsewell** [comment]
It should be quite easy to branch on the `v2.0.0a1` tag, and create a release from there, this is what I had to do with e.g. https://github.com/aiidateam/aiida-wannier90-workflows/tree/support-1.x
and this is why I mentioned about moving to https://github.com/aiidaplugins, there I would be happy to do all this myself (but no worries if you don't want to)

**Comment by azadoks** [comment]
Hey Chris, I have some updates to `aiida-abinit` that I need to do some quick testing with, then I'll put up a non-pre-release version on pypi.

For the version of Abinit, we're using some features in the common workflows project that require v9.3 or later, but it would be best to have the latest (v9.6.1) to avoid any issues (v9.4.x is safe as well).
