### ISSUE TITLE
AiiDA v2 compatibility?

### ISSUE THREAD

**Issue by ahkole** [sponce24/aiida-abinit#15]
Hello,

I was wondering whether there is already a release available that is compatible with v2+ of AiiDA? I see that there is a PR about v2 compatibility (https://github.com/sponce24/aiida-abinit/pull/14) but the plugin is still listed as only being compatible with >=v1.6.3, <1.7.0 in the AiiDA plugin list (https://aiidateam.github.io/aiida-registry/plugins/aiida-abinit.html).

**Comment by azadoks** [comment]
Hi,

The plugin should be compatible with AiiDA v2.x.
We're working on updating the registry to show this; if you try the plugin with v2 and experience any problems, please let us know!

**Comment by ahkole** [comment]
Okay, thanks for the clarification! I will give it a try.
