### ISSUE TITLE
Upgrade to `aiida-pseudo==0.6.0`

### ISSUE THREAD

**Issue by sphuber** [sponce24/aiida-abinit#2]
This version that was just released adds support for units for the recommended cutoffs to the pseudopotential families. Not only can you now specify cutoffs in "any" unit you want, so no need to convert anymore, since the unit will be stored in the database, the `family.get_recommended_cutoffs` now supports the argument `unit` which allows you to request the cutoffs in any energy unit.
See this PR for `aiida-quantumespresso` on how we adapted to it: https://github.com/aiidateam/aiida-quantumespresso/pull/671/files

**Comment by sphuber** [comment]
Looking a bit more in detail into the code, it seems that you won't actually need to change anything in this plugin but rather update the code in `aiida-common-workflows` which is where the automated cutoffs from the pseudo family are handled.

**Comment by zooks97** [comment]
Seem's like everything is alright here then, so I'll close this up.
